//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApplication1.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback initiateSesionOperationCompleted;
        
        private System.Threading.SendOrPostCallback initiateSesionRecepcionistOperationCompleted;
        
        private System.Threading.SendOrPostCallback dataClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback dataRecepcionistOperationCompleted;
        
        private System.Threading.SendOrPostCallback dataReserveOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteReserveOperationCompleted;
        
        private System.Threading.SendOrPostCallback addReserveOperationCompleted;
        
        private System.Threading.SendOrPostCallback addClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchClientWithNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getClientByRecepcionistOperationCompleted;
        
        private System.Threading.SendOrPostCallback modifyReserveOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::WebApplication1.Properties.Settings.Default.WebApplication1_localhost_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event initiateSesionCompletedEventHandler initiateSesionCompleted;
        
        /// <remarks/>
        public event initiateSesionRecepcionistCompletedEventHandler initiateSesionRecepcionistCompleted;
        
        /// <remarks/>
        public event dataClientCompletedEventHandler dataClientCompleted;
        
        /// <remarks/>
        public event dataRecepcionistCompletedEventHandler dataRecepcionistCompleted;
        
        /// <remarks/>
        public event dataReserveCompletedEventHandler dataReserveCompleted;
        
        /// <remarks/>
        public event deleteReserveCompletedEventHandler deleteReserveCompleted;
        
        /// <remarks/>
        public event addReserveCompletedEventHandler addReserveCompleted;
        
        /// <remarks/>
        public event addClientCompletedEventHandler addClientCompleted;
        
        /// <remarks/>
        public event searchClientWithNameCompletedEventHandler searchClientWithNameCompleted;
        
        /// <remarks/>
        public event getClientByRecepcionistCompletedEventHandler getClientByRecepcionistCompleted;
        
        /// <remarks/>
        public event modifyReserveCompletedEventHandler modifyReserveCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Login(int user) {
            object[] results = this.Invoke("Login", new object[] {
                        user});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(int user) {
            this.LoginAsync(user, null);
        }
        
        /// <remarks/>
        public void LoginAsync(int user, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        user}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/initiateSesion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable initiateSesion(string user, string pass) {
            object[] results = this.Invoke("initiateSesion", new object[] {
                        user,
                        pass});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void initiateSesionAsync(string user, string pass) {
            this.initiateSesionAsync(user, pass, null);
        }
        
        /// <remarks/>
        public void initiateSesionAsync(string user, string pass, object userState) {
            if ((this.initiateSesionOperationCompleted == null)) {
                this.initiateSesionOperationCompleted = new System.Threading.SendOrPostCallback(this.OninitiateSesionOperationCompleted);
            }
            this.InvokeAsync("initiateSesion", new object[] {
                        user,
                        pass}, this.initiateSesionOperationCompleted, userState);
        }
        
        private void OninitiateSesionOperationCompleted(object arg) {
            if ((this.initiateSesionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.initiateSesionCompleted(this, new initiateSesionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/initiateSesionRecepcionist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable initiateSesionRecepcionist(string user, string pass) {
            object[] results = this.Invoke("initiateSesionRecepcionist", new object[] {
                        user,
                        pass});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void initiateSesionRecepcionistAsync(string user, string pass) {
            this.initiateSesionRecepcionistAsync(user, pass, null);
        }
        
        /// <remarks/>
        public void initiateSesionRecepcionistAsync(string user, string pass, object userState) {
            if ((this.initiateSesionRecepcionistOperationCompleted == null)) {
                this.initiateSesionRecepcionistOperationCompleted = new System.Threading.SendOrPostCallback(this.OninitiateSesionRecepcionistOperationCompleted);
            }
            this.InvokeAsync("initiateSesionRecepcionist", new object[] {
                        user,
                        pass}, this.initiateSesionRecepcionistOperationCompleted, userState);
        }
        
        private void OninitiateSesionRecepcionistOperationCompleted(object arg) {
            if ((this.initiateSesionRecepcionistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.initiateSesionRecepcionistCompleted(this, new initiateSesionRecepcionistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dataClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable dataClient(int id) {
            object[] results = this.Invoke("dataClient", new object[] {
                        id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void dataClientAsync(int id) {
            this.dataClientAsync(id, null);
        }
        
        /// <remarks/>
        public void dataClientAsync(int id, object userState) {
            if ((this.dataClientOperationCompleted == null)) {
                this.dataClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OndataClientOperationCompleted);
            }
            this.InvokeAsync("dataClient", new object[] {
                        id}, this.dataClientOperationCompleted, userState);
        }
        
        private void OndataClientOperationCompleted(object arg) {
            if ((this.dataClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dataClientCompleted(this, new dataClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dataRecepcionist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable dataRecepcionist(int id) {
            object[] results = this.Invoke("dataRecepcionist", new object[] {
                        id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void dataRecepcionistAsync(int id) {
            this.dataRecepcionistAsync(id, null);
        }
        
        /// <remarks/>
        public void dataRecepcionistAsync(int id, object userState) {
            if ((this.dataRecepcionistOperationCompleted == null)) {
                this.dataRecepcionistOperationCompleted = new System.Threading.SendOrPostCallback(this.OndataRecepcionistOperationCompleted);
            }
            this.InvokeAsync("dataRecepcionist", new object[] {
                        id}, this.dataRecepcionistOperationCompleted, userState);
        }
        
        private void OndataRecepcionistOperationCompleted(object arg) {
            if ((this.dataRecepcionistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dataRecepcionistCompleted(this, new dataRecepcionistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dataReserve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable dataReserve(int id, int role) {
            object[] results = this.Invoke("dataReserve", new object[] {
                        id,
                        role});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void dataReserveAsync(int id, int role) {
            this.dataReserveAsync(id, role, null);
        }
        
        /// <remarks/>
        public void dataReserveAsync(int id, int role, object userState) {
            if ((this.dataReserveOperationCompleted == null)) {
                this.dataReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OndataReserveOperationCompleted);
            }
            this.InvokeAsync("dataReserve", new object[] {
                        id,
                        role}, this.dataReserveOperationCompleted, userState);
        }
        
        private void OndataReserveOperationCompleted(object arg) {
            if ((this.dataReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dataReserveCompleted(this, new dataReserveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteReserve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deleteReserve(int id) {
            this.Invoke("deleteReserve", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void deleteReserveAsync(int id) {
            this.deleteReserveAsync(id, null);
        }
        
        /// <remarks/>
        public void deleteReserveAsync(int id, object userState) {
            if ((this.deleteReserveOperationCompleted == null)) {
                this.deleteReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteReserveOperationCompleted);
            }
            this.InvokeAsync("deleteReserve", new object[] {
                        id}, this.deleteReserveOperationCompleted, userState);
        }
        
        private void OndeleteReserveOperationCompleted(object arg) {
            if ((this.deleteReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteReserveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addReserve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addReserve(int idRecepcionist, int idnClient, string arrivalDate, string finishDate, string typeRoom) {
            this.Invoke("addReserve", new object[] {
                        idRecepcionist,
                        idnClient,
                        arrivalDate,
                        finishDate,
                        typeRoom});
        }
        
        /// <remarks/>
        public void addReserveAsync(int idRecepcionist, int idnClient, string arrivalDate, string finishDate, string typeRoom) {
            this.addReserveAsync(idRecepcionist, idnClient, arrivalDate, finishDate, typeRoom, null);
        }
        
        /// <remarks/>
        public void addReserveAsync(int idRecepcionist, int idnClient, string arrivalDate, string finishDate, string typeRoom, object userState) {
            if ((this.addReserveOperationCompleted == null)) {
                this.addReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddReserveOperationCompleted);
            }
            this.InvokeAsync("addReserve", new object[] {
                        idRecepcionist,
                        idnClient,
                        arrivalDate,
                        finishDate,
                        typeRoom}, this.addReserveOperationCompleted, userState);
        }
        
        private void OnaddReserveOperationCompleted(object arg) {
            if ((this.addReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addReserveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addClient(int idnClient, string nameClient, string passClient, string surname, int creditCard, int idRecepcionist) {
            this.Invoke("addClient", new object[] {
                        idnClient,
                        nameClient,
                        passClient,
                        surname,
                        creditCard,
                        idRecepcionist});
        }
        
        /// <remarks/>
        public void addClientAsync(int idnClient, string nameClient, string passClient, string surname, int creditCard, int idRecepcionist) {
            this.addClientAsync(idnClient, nameClient, passClient, surname, creditCard, idRecepcionist, null);
        }
        
        /// <remarks/>
        public void addClientAsync(int idnClient, string nameClient, string passClient, string surname, int creditCard, int idRecepcionist, object userState) {
            if ((this.addClientOperationCompleted == null)) {
                this.addClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddClientOperationCompleted);
            }
            this.InvokeAsync("addClient", new object[] {
                        idnClient,
                        nameClient,
                        passClient,
                        surname,
                        creditCard,
                        idRecepcionist}, this.addClientOperationCompleted, userState);
        }
        
        private void OnaddClientOperationCompleted(object arg) {
            if ((this.addClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addClientCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/searchClientWithName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable searchClientWithName(string name) {
            object[] results = this.Invoke("searchClientWithName", new object[] {
                        name});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void searchClientWithNameAsync(string name) {
            this.searchClientWithNameAsync(name, null);
        }
        
        /// <remarks/>
        public void searchClientWithNameAsync(string name, object userState) {
            if ((this.searchClientWithNameOperationCompleted == null)) {
                this.searchClientWithNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchClientWithNameOperationCompleted);
            }
            this.InvokeAsync("searchClientWithName", new object[] {
                        name}, this.searchClientWithNameOperationCompleted, userState);
        }
        
        private void OnsearchClientWithNameOperationCompleted(object arg) {
            if ((this.searchClientWithNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchClientWithNameCompleted(this, new searchClientWithNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getClientByRecepcionist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getClientByRecepcionist(int idRecepcionist) {
            object[] results = this.Invoke("getClientByRecepcionist", new object[] {
                        idRecepcionist});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getClientByRecepcionistAsync(int idRecepcionist) {
            this.getClientByRecepcionistAsync(idRecepcionist, null);
        }
        
        /// <remarks/>
        public void getClientByRecepcionistAsync(int idRecepcionist, object userState) {
            if ((this.getClientByRecepcionistOperationCompleted == null)) {
                this.getClientByRecepcionistOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetClientByRecepcionistOperationCompleted);
            }
            this.InvokeAsync("getClientByRecepcionist", new object[] {
                        idRecepcionist}, this.getClientByRecepcionistOperationCompleted, userState);
        }
        
        private void OngetClientByRecepcionistOperationCompleted(object arg) {
            if ((this.getClientByRecepcionistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getClientByRecepcionistCompleted(this, new getClientByRecepcionistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/modifyReserve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void modifyReserve(int reserve, int idnClient, string arrivalDate, string finishdate, string typeRoom) {
            this.Invoke("modifyReserve", new object[] {
                        reserve,
                        idnClient,
                        arrivalDate,
                        finishdate,
                        typeRoom});
        }
        
        /// <remarks/>
        public void modifyReserveAsync(int reserve, int idnClient, string arrivalDate, string finishdate, string typeRoom) {
            this.modifyReserveAsync(reserve, idnClient, arrivalDate, finishdate, typeRoom, null);
        }
        
        /// <remarks/>
        public void modifyReserveAsync(int reserve, int idnClient, string arrivalDate, string finishdate, string typeRoom, object userState) {
            if ((this.modifyReserveOperationCompleted == null)) {
                this.modifyReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodifyReserveOperationCompleted);
            }
            this.InvokeAsync("modifyReserve", new object[] {
                        reserve,
                        idnClient,
                        arrivalDate,
                        finishdate,
                        typeRoom}, this.modifyReserveOperationCompleted, userState);
        }
        
        private void OnmodifyReserveOperationCompleted(object arg) {
            if ((this.modifyReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modifyReserveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void initiateSesionCompletedEventHandler(object sender, initiateSesionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class initiateSesionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal initiateSesionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void initiateSesionRecepcionistCompletedEventHandler(object sender, initiateSesionRecepcionistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class initiateSesionRecepcionistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal initiateSesionRecepcionistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void dataClientCompletedEventHandler(object sender, dataClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dataClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dataClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void dataRecepcionistCompletedEventHandler(object sender, dataRecepcionistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dataRecepcionistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dataRecepcionistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void dataReserveCompletedEventHandler(object sender, dataReserveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dataReserveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dataReserveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void deleteReserveCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void addReserveCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void addClientCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void searchClientWithNameCompletedEventHandler(object sender, searchClientWithNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchClientWithNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchClientWithNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getClientByRecepcionistCompletedEventHandler(object sender, getClientByRecepcionistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getClientByRecepcionistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getClientByRecepcionistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void modifyReserveCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591